version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "devmon"]
    # command: ["tail", "-f", "/dev/null"]
    ports:
      - '3330:3330'
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
    depends_on:
      - mongo
    networks:
      - myapp-network

  mongo:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongostat", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - myapp-network

networks:
  myapp-network:

volumes:
  mongo-data: