version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "dev"]
    ports:
      - '3330:3330'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/node-auth
    depends_on:
      - mongodb
    networks:
      - myapp-network


  mongodb:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongostat", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - myapp-network

networks:
  myapp-network:

volumes:
  mongo-data: